### ISSUE TITLE
Testing "HTTPS" on Data Tracker pages

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#121]
Requester: **John**
Group: **DTS**

Asking to test map widgets in Data Tracker using `https`. Knack has changed some aspects to their maps and we're thinking of changing over to `https` on the Data Tracker.

Please test the following:
- [ ] [Performance Dashboards](http://transportation.austintexas.io/)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/890ee0c7-78aa-4722-9f58-e2a8abd58857)
- [ ] TMC pages
- [ ] Signal Work Orders
- [ ] Signs and Markings Work Orders - I can show you which pages if you need clarification on this

[Data Tracker Test vs Live Comparisons.xlsx](https://github.com/cityofaustin/atd-knack-data-tracker/files/3298372/Data.Tracker.Test.vs.Live.Comparisons.xlsx)
