### ISSUE TITLE
Signal Status "Contractor Controlled" + date taken by contractor

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#153]
Ben Plett
TMC

Requesting
>In the TMC, it would be very helpful to us if we had a Signal status of "Contractor Controlled" and then a field showing the date that it was taken over by the contractor. It would also be good to have date that we took it back. 

Proposing 
- [ ] Asking for a new choice on `Signal Status` field - "Contractor Controlled"
- [ ] New field `Contractor Controlled Date`
- [ ] New field `Take back Date`?
