### ISSUE TITLE
Clean up accounts in Data Tracker Production

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#188]
- [ ] Remove Signs and Markings technicians from Data Tracker Prod? 
- Keep only people entering performance measures?

**Comment by dianamartin** [comment]
Was reviewing accounts in Prod.
- [x] cleared `User Roles` and `GRANT_USER_ROLES` of those accounts that were listed as `inactive`.

Need list from Signs and Markings who still needs access to Data Tracker Prod

**Comment by amenity** [comment]
Also remove unused user roles

**Comment by dianamartin** [comment]
- [x] Set all `Signs & Markings | Technicians` status to - Inactive
- [x] Removed user roles except `Viewer` on remaining Signs & Markings support staff accounts
- [x] Deleted user role: `Supervisor | Signs & Markings` 
- [x] Deleted user role: `Technician | Signs & Markings`
